
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankapp
      version: blue
  template:
    metadata:
      labels:
        app: bankapp
        version: blue
    spec:
      containers:
      - name: bankapp
        image: ammb/bankapp:blue # Adjust the image tag for the blue version
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value-from: secrets
        - name: SPRING_DATASOURCE_USERNAME
          value-from: secrets
        - name: SPRING_DATASOURCE_PASSWORD
          value-from: secrets
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"